<a href="https://colab.research.google.com/github/laiminhquan2k5-coder/Tri_Tue_Nhan_Tao_Nhom14/blob/main/tienxulydulieu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =============================================================================
# PREPROCESSING PIPELINE
# 2.3.1 Lowercase
# 2.3.2 Remove punctuation
# 2.3.3 Remove URL
# =============================================================================

import pandas as pd
import re
import string

# =============================================================================
# 1. LOAD DỮ LIỆU
# =============================================================================

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Shoes_Train_Data.xlsx')

# Chọn 10 dòng đầu để minh họa
sample_df = df[["Review"]].head(10).copy()

print("=" * 70)
print("BƯỚC 0 — DỮ LIỆU GỐC")
print("=" * 70)

display(sample_df)


# =============================================================================
# 2.3.1 LOWERCASE
# =============================================================================

sample_df["Review_Lowercase"] = (
    sample_df["Review"]
    .astype(str)
    .str.lower()
)

print("=" * 70)
print("BƯỚC 1 — LOWERCASE")
print("=" * 70)

display(sample_df[["Review", "Review_Lowercase"]])


# =============================================================================
# 2.3.3 REMOVE URL
# =============================================================================

url_pattern = r'https?://\S+|www\.\S+'

sample_df["Review_NoURL"] = (
    sample_df["Review_Lowercase"]
    .str.replace(url_pattern, '', regex=True)
)

print("=" * 70)
print("BƯỚC 2 — REMOVE URL")
print("=" * 70)

display(sample_df[["Review_Lowercase", "Review_NoURL"]])


# =============================================================================
# 2.3.2 REMOVE PUNCTUATION
# =============================================================================

punct_table = str.maketrans('', '', string.punctuation)

sample_df["Review_Preprocessed"] = (
    sample_df["Review_NoURL"]
    .str.translate(punct_table)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print("=" * 70)
print("BƯỚC 3 — REMOVE PUNCTUATION")
print("=" * 70)

display(sample_df[["Review_NoURL", "Review_Preprocessed"]])


# =============================================================================
# 5. BẢNG MINH HỌA TRƯỚC / SAU PREPROCESSING
# =============================================================================

print("=" * 70)
print("BƯỚC 4 — BẢNG MINH HỌA TRƯỚC VÀ SAU PREPROCESSING")
print("=" * 70)

display(sample_df[
    [
        "Review",
        "Review_Lowercase",
        "Review_NoURL",
        "Review_Preprocessed"
    ]
])

======================================================================
BƯỚC 0 — DỮ LIỆU GỐC
======================================================================

                                              Review
0                                Giày đẹp, đi êm lắm
1  Mình săn sale với giá khá rẻ Chất lượng ok  Sh...
2  Hình ảnh và video chỉ mang tính chất minh họa ...
3  Mình đặt size 39 nhưng chật k đeo nổi. Còn giầ...
4           Nên mua nha mọi người đẹp xuất sắc lun ạ
5  Giày đẹp giống hình, mọi người nên mua tăng 1 ...
6                    Đặt đế đen giao đế trắng là sao
7   Hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa
8  Đặt hàng từ hôm 21 nay 27 mới nhận đc giày Châ...
9  Đã mua của shop mấy lần rồi, sản phẩm uy tín y...

======================================================================
BƯỚC 1 — LOWERCASE
======================================================================

,Review,Review_Lowercase
0,"Giày đẹp, đi êm lắm","giày đẹp, đi êm lắm"
1,Mình săn sale với giá khá rẻ Chất lượng ok Sh...,mình săn sale với giá khá rẻ chất lượng ok sh...
2,Hình ảnh và video chỉ mang tính chất minh họa ...,hình ảnh và video chỉ mang tính chất minh họa ...
3,Mình đặt size 39 nhưng chật k đeo nổi. Còn giầ...,mình đặt size 39 nhưng chật k đeo nổi. còn giầ...
4,Nên mua nha mọi người đẹp xuất sắc lun ạ,nên mua nha mọi người đẹp xuất sắc lun ạ
5,"Giày đẹp giống hình, mọi người nên mua tăng 1 ...","giày đẹp giống hình, mọi người nên mua tăng 1 ..."
6,Đặt đế đen giao đế trắng là sao,đặt đế đen giao đế trắng là sao
7,Hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa
8,Đặt hàng từ hôm 21 nay 27 mới nhận đc giày Châ...,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...
9,"Đã mua của shop mấy lần rồi, sản phẩm uy tín y...","đã mua của shop mấy lần rồi, sản phẩm uy tín y..."

======================================================================
BƯỚC 2 — REMOVE URL
======================================================================

,Review_Lowercase,Review_NoURL
0,"giày đẹp, đi êm lắm","giày đẹp, đi êm lắm"
1,mình săn sale với giá khá rẻ chất lượng ok sh...,mình săn sale với giá khá rẻ chất lượng ok sh...
2,hình ảnh và video chỉ mang tính chất minh họa ...,hình ảnh và video chỉ mang tính chất minh họa ...
3,mình đặt size 39 nhưng chật k đeo nổi. còn giầ...,mình đặt size 39 nhưng chật k đeo nổi. còn giầ...
4,nên mua nha mọi người đẹp xuất sắc lun ạ,nên mua nha mọi người đẹp xuất sắc lun ạ
5,"giày đẹp giống hình, mọi người nên mua tăng 1 ...","giày đẹp giống hình, mọi người nên mua tăng 1 ..."
6,đặt đế đen giao đế trắng là sao,đặt đế đen giao đế trắng là sao
7,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa
8,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...
9,"đã mua của shop mấy lần rồi, sản phẩm uy tín y...","đã mua của shop mấy lần rồi, sản phẩm uy tín y..."

======================================================================
BƯỚC 3 — REMOVE PUNCTUATION
======================================================================

,Review_NoURL,Review_Preprocessed
0,"giày đẹp, đi êm lắm",giày đẹp đi êm lắm
1,mình săn sale với giá khá rẻ chất lượng ok sh...,mình săn sale với giá khá rẻ chất lượng ok shi...
2,hình ảnh và video chỉ mang tính chất minh họa ...,hình ảnh và video chỉ mang tính chất minh họa ...
3,mình đặt size 39 nhưng chật k đeo nổi. còn giầ...,mình đặt size 39 nhưng chật k đeo nổi còn giầy...
4,nên mua nha mọi người đẹp xuất sắc lun ạ,nên mua nha mọi người đẹp xuất sắc lun ạ
5,"giày đẹp giống hình, mọi người nên mua tăng 1 ...",giày đẹp giống hình mọi người nên mua tăng 1 s...
6,đặt đế đen giao đế trắng là sao,đặt đế đen giao đế trắng là sao
7,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa
8,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...
9,"đã mua của shop mấy lần rồi, sản phẩm uy tín y...",đã mua của shop mấy lần rồi sản phẩm uy tín y ...

======================================================================
BƯỚC 4 — BẢNG MINH HỌA TRƯỚC VÀ SAU PREPROCESSING
======================================================================

,Review,Review_Lowercase,Review_NoURL,Review_Preprocessed
0,"Giày đẹp, đi êm lắm","giày đẹp, đi êm lắm","giày đẹp, đi êm lắm",giày đẹp đi êm lắm
1,Mình săn sale với giá khá rẻ Chất lượng ok Sh...,mình săn sale với giá khá rẻ chất lượng ok sh...,mình săn sale với giá khá rẻ chất lượng ok sh...,mình săn sale với giá khá rẻ chất lượng ok shi...
2,Hình ảnh và video chỉ mang tính chất minh họa ...,hình ảnh và video chỉ mang tính chất minh họa ...,hình ảnh và video chỉ mang tính chất minh họa ...,hình ảnh và video chỉ mang tính chất minh họa ...
3,Mình đặt size 39 nhưng chật k đeo nổi. Còn giầ...,mình đặt size 39 nhưng chật k đeo nổi. còn giầ...,mình đặt size 39 nhưng chật k đeo nổi. còn giầ...,mình đặt size 39 nhưng chật k đeo nổi còn giầy...
4,Nên mua nha mọi người đẹp xuất sắc lun ạ,nên mua nha mọi người đẹp xuất sắc lun ạ,nên mua nha mọi người đẹp xuất sắc lun ạ,nên mua nha mọi người đẹp xuất sắc lun ạ
5,"Giày đẹp giống hình, mọi người nên mua tăng 1 ...","giày đẹp giống hình, mọi người nên mua tăng 1 ...","giày đẹp giống hình, mọi người nên mua tăng 1 ...",giày đẹp giống hình mọi người nên mua tăng 1 s...
6,Đặt đế đen giao đế trắng là sao,đặt đế đen giao đế trắng là sao,đặt đế đen giao đế trắng là sao,đặt đế đen giao đế trắng là sao
7,Hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa,hàng đẹp giao nhanh shop nhiệt tình ảnh minh họa
8,Đặt hàng từ hôm 21 nay 27 mới nhận đc giày Châ...,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...,đặt hàng từ hôm 21 nay 27 mới nhận đc giày châ...
9,"Đã mua của shop mấy lần rồi, sản phẩm uy tín y...","đã mua của shop mấy lần rồi, sản phẩm uy tín y...","đã mua của shop mấy lần rồi, sản phẩm uy tín y...",đã mua của shop mấy lần rồi sản phẩm uy tín y ...